name: icthubx
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  flutter_bloc: ^8.1.3
  zoom_widget: ^2.0.1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#300046"
  image: images/icona.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icona.png"
flutter:

  uses-material-design: true

  assets:
    - images/
    - fonts/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Urbanist
       fonts:
         - asset: fonts/Urbanist-Regular.ttf
     - family: UrbanistBold
       fonts:
         - asset: fonts/Urbanist-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
